Added checking ROS Dependencies to ROS 2 CI
Signed-off-by: Pyo <pyo@robotis.com>

diff --git a/.github/workflows/ros-ci.yml b/.github/workflows/ros-ci.yml
--- a/.github/workflows/ros-ci.yml
+++ b/.github/workflows/ros-ci.yml
@@ -49,6 +49,19 @@ jobs:
         with:
           required-ros-distributions: ${{ matrix.ros_distribution }}
 
+      - name: Check ROS Dependencies
+        shell: bash
+        run: |
+          set -e
+          source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
+          echo "--- Performing rosdep check for ROS 2 ${{ matrix.ros_distribution }} ---"
+          if rosdep check --from-paths src --ignore-src --rosdistro ${{ matrix.ros_distribution }}; then
+            echo "--- rosdep check passed ---"
+          else
+            echo "--- rosdep check failed: Missing system dependencies or unresolvable keys. ---"
+            exit 1
+          fi
+
       - name: Build and Test
         uses: ros-tooling/action-ros-ci@v0.3
         with:
